import {
  Plus,
  Activity,
  Clock,
  Calendar,
  User,
  TrendingUp,
} from "lucide-react";
import { LeadStatus } from "@/types/lead";

export const statusConfig = {
  [LeadStatus.NEW]: {
    title: "New Leads",
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    icon: Plus,
  },
  [LeadStatus.DNP]: {
    title: "DNP",
    color: "text-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    icon: Activity,
  },
  [LeadStatus.FOLLOW_UP]: {
    title: "Follow-up",
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    icon: Clock,
  },
  [LeadStatus.CLOSE]: {
    title: "Closed",
    color: "text-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    icon: Activity,
  },
  [LeadStatus.OPD_SCHEDULE]: {
    title: "OPD Schedule",
    color: "text-cyan-600",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
    icon: Calendar,
  },
  [LeadStatus.OPD_DONE]: {
    title: "OPD Done",
    color: "text-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    icon: User,
  },
  [LeadStatus.IPD_SCHEDULE]: {
    title: "IPD Schedule",
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    icon: Calendar,
  },
  [LeadStatus.IPD_DONE]: {
    title: "IPD Done",
    color: "text-emerald-600",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    icon: User,
  },
  [LeadStatus.IPD_LOSE]: {
    title: "IPD Lose",
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
    icon: Activity,
  },
  [LeadStatus.HOT_LEAD]: {
    title: "Hot Lead",
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    icon: TrendingUp,
  },
  [LeadStatus.COLD_LEAD]: {
    title: "Cold Lead",
    color: "text-gray-600",
    bgColor: "bg-gray-50",
    borderColor: "border-gray-200",
    icon: Activity,
  },
  [LeadStatus.WARM_LEAD]: {
    title: "Warm Lead",
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    icon: TrendingUp,
  },
  [LeadStatus.IRREVERENT]: {
    title: "Irreverent",
    color: "text-stone-600",
    bgColor: "bg-stone-50",
    borderColor: "border-stone-200",
    icon: Activity,
  },
  [LeadStatus.FUND_ISSUE]: {
    title: "Fund Issue",
    color: "text-yellow-600",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
    icon: Activity,
  },
  [LeadStatus.OUTSIDE_OUR_REACH]: {
    title: "Outside our Reach",
    color: "text-zinc-600",
    bgColor: "bg-zinc-50",
    borderColor: "border-zinc-200",
    icon: Activity,
  },
  [LeadStatus.SURGERY_NOT_SUGGESTED]: {
    title: "Surgery Not Suggested",
    color: "text-neutral-600",
    bgColor: "bg-neutral-50",
    borderColor: "border-neutral-200",
    icon: Activity,
  },
  [LeadStatus.ENQUIRED_FOR_OTHER_PERSON]: {
    title: "Enquired for Other Person",
    color: "text-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    icon: User,
  },
};
